<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AlatKerjaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('alat_kerjas')->insert([
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Chain Saw 20"',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 36,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 23,
                'keterangan' => 'Digunakan untuk pemotongan kayu.',
                'tgl_akhir_kontrak' => '2025-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Teropong',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 30,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 17,
                'keterangan' => 'Alat pengamatan jarak jauh.',
                'tgl_akhir_kontrak' => '2024-12-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Arit Sawit',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 24,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 11,
                'keterangan' => 'Untuk pemotongan pelepah sawit.',
                'tgl_akhir_kontrak' => '2024-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Handy Talky Dual Band',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 60,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 47,
                'keterangan' => 'Alat komunikasi proyek.',
                'tgl_akhir_kontrak' => '2027-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Sepatu Karet',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 12,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => -1,
                'keterangan' => 'Kondisi kritis, perlu penggantian.',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'AVL (Automatic Vehicle Locater)',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 36,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 23,
                'keterangan' => 'Untuk pelacakan kendaraan proyek.',
                'tgl_akhir_kontrak' => '2025-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Groundcluster',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 48,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 35,
                'keterangan' => 'Digunakan untuk grounding.',
                'tgl_akhir_kontrak' => '2026-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Full Body Harness + Lock Lanyard',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 24,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 11,
                'keterangan' => 'NORMAL',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Ear Muff',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 12,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => -1,
                'keterangan' => 'KRONIS',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Ear Plug',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 12,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => -1,
                'keterangan' => 'KRONIS',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Seragam',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 12,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => -1,
                'keterangan' => 'KRONIS',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Sarung Tangan 20kV',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 24,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 11,
                'keterangan' => 'NORMAL',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Sepatu Safety',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 12,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => -1,
                'keterangan' => 'KRONIS',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Safety Shoes 20kV',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 24,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 11,
                'keterangan' => 'NORMAL',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Helm Safety',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 12,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => -1,
                'keterangan' => 'KRONIS',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Jas Hujan',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 12,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => -1,
                'keterangan' => 'KRONIS',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Rompi',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 12,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => -1,
                'keterangan' => 'KRONIS',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Kotak P3K',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 12,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => -1,
                'keterangan' => 'KRONIS',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Dispenser',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 12,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => -1,
                'keterangan' => 'KRONIS',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Laptop',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 60,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 47,
                'keterangan' => 'NORMAL',
                'tgl_akhir_kontrak' => '2027-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Printer',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 60,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 47,
                'keterangan' => 'NORMAL',
                'tgl_akhir_kontrak' => '2027-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Meja',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 60,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 47,
                'keterangan' => 'NORMAL',
                'tgl_akhir_kontrak' => '2027-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Kursi',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 60,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 47,
                'keterangan' => 'NORMAL',
                'tgl_akhir_kontrak' => '2027-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'ID CARD',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 12,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => -1,
                'keterangan' => 'KRONIS',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Lampu Senter Re-Charger',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 12,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => -1,
                'keterangan' => 'KRONIS',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Lampu Sorot 12 Volt 55 Watt',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 12,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => -1,
                'keterangan' => 'KRONIS',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Tool set mekanik (< 1000 kW)',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 36,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 23,
                'keterangan' => 'NORMAL',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Tool set electrik, Alat Ukur dan Instrument',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 36,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 23,
                'keterangan' => 'NORMAL',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Radio Komunikasi',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 36,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 23,
                'keterangan' => 'NORMAL',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'project_id' => '96dea534-8994-46c2-89d4-83bf1b01e810',
                'nama_alat' => 'Radio Base Station',
                'tgl_kontrak' => '2022-06-30',
                'masa_pakai' => 36,
                'masa_pakai_saat_ini' => 13,
                'sisa_masa_pakai' => 23,
                'keterangan' => 'NORMAL',
                'tgl_akhir_kontrak' => '2023-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
